# Generated by Django 4.1.7 on 2024-04-29 07:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BillSoftwareapp', '0011_alter_history_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 4, 29)),
        ),
        migrations.AlterField(
            model_name='purchasedebit',
            name='billdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
